services:

  nodejs-app:
    container_name : ${ENV_TYPE}_nodejswebappcontainername # används för docker-intern DNS
    build :
      context: webapp
      
  nginx-proxy:
    image: nginx
    container_name: ${ENV_TYPE}_nginx
    ports:
      - ${NGINX_EXPOSED_PORT}:8080 
    depends_on:
      - nodejs-app 
    volumes:
      - type: bind
        source: ./nginx/nginx.${ENV_TYPE}.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true    
      - ./nginx/webroot:/www/web-root