services:

  nodejs-app:
    container_name : ${ENV_TYPE}nodejswebappcontainername # används för docker-intern DNS
    build :
      context: webapp
    # ports:
    #   - "3000:3000"

  nginx-proxy:
    image: nginx
    container_name: ${ENV_TYPE}nginx
    ports:
      - ${NGINX_EXPOSED_PORT}:8080 
    depends_on:
      - nodejs-app 
    volumes:
      - type: bind
        source: ./nginx/nginx.${ENV_TYPE}.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true    
      - ./nginx/webroot:/www/web-root